### PR TITLE
WIP: Added Option to create custom Label Formatter

### PR DESCRIPTION
**Pull request by AKuederle**
Hey,

I added the option to completely customize the unit label by providing a label_formatter (a function that takes the value and the unit as input and outputs the label string). This should help in all cases, were you need something completely custom or as a quick fix, if non of the predefined units work.

I am not happy with the tests yet, but they should cover the main functionality. If you are interested in merging that feature, I will add an example and a Note in the README.

Regards,
Arne

### CODE REVIEW

**Comment by ppinard** [comment]
Thank you for the contribution. It looks like a useful feature. Could you add a set/get/property methods for the `label_formatter` like for the other options? Look at `get_dx`/`set_dx`/`dx` for an example. Also formatter should take two "t" (see http://matplotlib.org/api/ticker_api.html).

I realized I need to modify the README to differentiate between the `__init__` arguments and the matplotlibrc parameters. I will try to make this modification this week. You can then add the documentation for the `label_formatter`.

**Comment by AKuederle** [comment]
Ok, should I include strict type checking? So checking if the formatter is a function and can take at least 2 arguments? 

Something like this:

```python
six.get_function_code(formatter).co_argcount
```

**Comment by ppinard** [comment]
I don't think the type checking is necessary. The other arguments are not checked, and it's Python after all :)

**Comment by AKuederle** [comment]
But then we do not need setters and getters, or? As a normal class parameter it can just be modified without them

**Comment by ppinard** [comment]
I agree, but I tried to replicate the internal structure of matplotlib. I do not know the reason why, but all properties have setters and getters. Take a look at the `Artist` class and the property [picker](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/artist.py#L495).

**Comment by AKuederle** [comment]
Ok then. I added some setter and getters and fixed the typing error. And I added the PyCharm (IDE)  config folder to the gitignore. I hope you do not mind.

**Comment by AKuederle** [comment]
Ok now it is working. I should not just blindly copy and paste and run tests before pushing. Sorry for the additional commit.

**Comment by cphyc** [comment]
Hi all! Should it be merged?

**Comment by AKuederle** [comment]
If @ppinard is happy with the code, I will add documentation for this feature.

**Comment by ppinard** [comment]
Sorry for my inaction. I updated the README.rst in the master branch with a section about the arguments of the ScaleBar constructor. @AKuederle Could you copy the documentation for the `label_formatter` there? After this, I will merge and create a new release. 0.3.0!

**Comment by cphyc** [comment]
Awesome! Thanks

**Comment by AKuederle** [comment]
I added some documentation. Ready to merge from my side

**Comment by ppinard** [comment]
I see that you added the file `.eggs/README.txt`. Is this file really necessary? Apart from that, everything looks good. Thank you.

**Comment by AKuederle** [comment]
Oh I see. That was not intentially. The file must have been autogenerated when I was testing the installation. I am really sorry that I did not checked that. I will add another commit and remove it.

**Comment by ppinard** [comment]
The changes are now on PyPi in version [0.3.1](https://pypi.python.org/pypi/matplotlib-scalebar/0.3.1).

**Pull request merged**
