### PR TITLE
Force certain scale bar length

### PR DESCRIPTION
**Pull request by ppinard**
See issue #9

### CODE REVIEW

**Comment by ppinard** [comment]
@habi if you want some time, could let me know if this pull request solves #9. There is an example how to use the *fixed* mode in [example3.py](https://github.com/ppinard/matplotlib-scalebar/blob/fixed_value/doc/example3.py).

**Comment by habi** [comment]
> @habi if you want some time, could let me know if this pull request solves #9.
> 
Awesome, thanks!
I'm on vacation until Wednesday, will try to test then.

**Comment by pskeshu** [comment]
This is exactly what I'm looking for. It would be really nice if this feature is out on the next point release as early as possible. :)

**Comment by habi** [comment]
Sorry for not getting back to you earlier, I forgot about it after my vacation.
Now I wanted to user the (awesome) scalebar library again and then it came back to my mind.
The new addition/branch does exactly what I envisioned, **thanks a lot**!

**Comment by ppinard** [comment]
@habi thank you for your request and checking that the changes work.
@habi and @pskeshu this modification is now on PyPI (version 0.4.0).

**Pull request merged**
